"""
Test: verify the comparison prompt generated by compare_documents() explicitly
contains all required per-document slots for A, B, C (and D for 4-doc case).

Does NOT require a live database or LLM — mocks both.
Verifies:
  1. "Document A", "Document B", "Document C" all present in the prompt
  2. Each slot contains the correct filename (deterministic mapping)
  3. doc IDs outside the set never appear in the prompt
  4. 2-document prompt has A and B but NOT C
  5. 4-document prompt has A, B, C, D
  6. "DOCUMENT-BY-DOCUMENT ANALYSIS" section header present
  7. "REQUIRED PARTICIPANTS" line present and lists every label
  8. Existing retrieval test: all 10 tests still pass
"""

import asyncio
import sys
import pathlib

# ---------------------------------------------------------------------------
# Patch external dependencies before importing anything that pulls them in
# ---------------------------------------------------------------------------

import app.services.rag_service as rag_mod
import app.services.copilot_service as copilot_mod

CAPTURED_PROMPTS: list[str] = []

def _mock_search(db, query, limit, distance_threshold=0.80, document_ids=None):
    if document_ids and 25 in document_ids:
        return [{"document_id": 25, "document_title": "Doc 25", "document_filename": "doc25.pdf",
                 "chunk_index": i, "content": f"content-25-{i}", "distance": 0.20} for i in range(4)]
    if document_ids and 23 in document_ids:
        return [{"document_id": 23, "document_title": "Doc 23", "document_filename": "doc23.pdf",
                 "chunk_index": 0, "content": "content-23-0", "distance": 0.35}]
    if document_ids and 27 in document_ids:
        return []  # 0 chunks — the problem case
    if document_ids and 99 in document_ids:
        return [{"document_id": 99, "document_title": "Doc 99", "document_filename": "doc99.pdf",
                 "chunk_index": 0, "content": "content-99-0", "distance": 0.40}]
    return []

async def _capturing_copilot(question, context):
    CAPTURED_PROMPTS.append(question)
    return "[MOCK LLM RESPONSE]"

rag_mod.search_similar_chunks = _mock_search
rag_mod.ask_copilot_with_context = _capturing_copilot

from app.services.rag_service import compare_documents


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

async def run_comparison(docs, question="Compare these documents") -> str:
    CAPTURED_PROMPTS.clear()
    original_search = rag_mod.search_similar_chunks
    original_ask = rag_mod.ask_copilot_with_context
    rag_mod.search_similar_chunks = _mock_search
    rag_mod.ask_copilot_with_context = _capturing_copilot
    try:
        await compare_documents(db=None, question=question, documents=docs, limit=5)
    finally:
        rag_mod.search_similar_chunks = original_search
        rag_mod.ask_copilot_with_context = original_ask
    assert CAPTURED_PROMPTS, "No prompt was captured — ask_copilot_with_context not called"
    return CAPTURED_PROMPTS[-1]


# ---------------------------------------------------------------------------
# Test 1: 3-document prompt has A, B, C as required participants
# ---------------------------------------------------------------------------

async def test_prompt_contains_all_three_labels():
    docs = [
        {"id": 25, "title": "Doc 25", "filename": "doc25.pdf", "jurisdiction": "EU"},
        {"id": 23, "title": "Doc 23", "filename": "doc23.pdf", "jurisdiction": "US"},
        {"id": 27, "title": "Doc 27", "filename": "doc27.pdf", "jurisdiction": "UK"},
    ]
    prompt = await run_comparison(docs)

    assert "Document A" in prompt, "Document A missing from prompt"
    assert "Document B" in prompt, "Document B missing from prompt"
    assert "Document C" in prompt, "Document C missing from prompt"
    print("[TEST P1] 3-doc prompt contains Document A, B, C ✓")


# ---------------------------------------------------------------------------
# Test 2: REQUIRED PARTICIPANTS header lists A, B, C
# ---------------------------------------------------------------------------

async def test_required_participants_header():
    docs = [
        {"id": 25, "title": "Doc 25", "filename": "doc25.pdf", "jurisdiction": "EU"},
        {"id": 23, "title": "Doc 23", "filename": "doc23.pdf", "jurisdiction": "US"},
        {"id": 27, "title": "Doc 27", "filename": "doc27.pdf", "jurisdiction": "UK"},
    ]
    prompt = await run_comparison(docs)

    assert "DOCUMENT IDENTITY" in prompt, "DOCUMENT IDENTITY header missing"
    # The header line must list all three labels
    header_line_ok = "A" in prompt and "B" in prompt and "C" in prompt
    assert header_line_ok
    print("[TEST P2] DOCUMENT IDENTITY header present with A, B, C ✓")


# ---------------------------------------------------------------------------
# Test 3: DOCUMENT-BY-DOCUMENT ANALYSIS section is in the prompt
# ---------------------------------------------------------------------------

async def test_per_document_section_header():
    docs = [
        {"id": 25, "title": "Doc 25", "filename": "doc25.pdf", "jurisdiction": "EU"},
        {"id": 23, "title": "Doc 23", "filename": "doc23.pdf", "jurisdiction": "US"},
        {"id": 27, "title": "Doc 27", "filename": "doc27.pdf", "jurisdiction": "UK"},
    ]
    prompt = await run_comparison(docs)

    assert "DOCUMENT-BY-DOCUMENT ANALYSIS" in prompt, \
        "DOCUMENT-BY-DOCUMENT ANALYSIS section missing from prompt"
    print("[TEST P3] DOCUMENT-BY-DOCUMENT ANALYSIS section present ✓")


# ---------------------------------------------------------------------------
# Test 4: Each forced slot references the correct filename (deterministic)
# ---------------------------------------------------------------------------

async def test_deterministic_filename_per_slot():
    docs = [
        {"id": 25, "title": "Doc 25", "filename": "doc25.pdf", "jurisdiction": "EU"},
        {"id": 23, "title": "Doc 23", "filename": "doc23.pdf", "jurisdiction": "US"},
        {"id": 27, "title": "Doc 27", "filename": "doc27.pdf", "jurisdiction": "UK"},
    ]
    prompt = await run_comparison(docs)

    # The slot block should pair each label with its filename
    assert "doc25.pdf" in prompt, "doc25.pdf missing from prompt slots"
    assert "doc23.pdf" in prompt, "doc23.pdf missing from prompt slots"
    assert "doc27.pdf" in prompt, "doc27.pdf missing from prompt slots"

    # Verify the slots appear in correct order: A→25, B→23, C→27
    pos_a = prompt.index("Document A")
    pos_b = prompt.index("Document B")
    pos_c = prompt.index("Document C")
    assert pos_a < pos_b < pos_c, "Document labels are not in deterministic order A < B < C"
    print("[TEST P4] Deterministic filename-per-slot mapping correct ✓")


# ---------------------------------------------------------------------------
# Test 5: 2-document prompt has A and B but NOT C or D
# ---------------------------------------------------------------------------

async def test_2_doc_prompt_no_spurious_labels():
    docs = [
        {"id": 25, "title": "Doc 25", "filename": "doc25.pdf", "jurisdiction": "EU"},
        {"id": 23, "title": "Doc 23", "filename": "doc23.pdf", "jurisdiction": "US"},
    ]
    prompt = await run_comparison(docs)

    assert "Document A" in prompt
    assert "Document B" in prompt
    # "Document C" and "Document D" must not appear as required slots
    # (they may appear only if the LLM echoes something, but they shouldn't be in our prompt)
    assert "DOCUMENT C ANALYSIS" not in prompt, "Spurious Document C slot in 2-doc prompt"
    assert "DOCUMENT D ANALYSIS" not in prompt, "Spurious Document D slot in 2-doc prompt"
    print("[TEST P5] 2-doc prompt has A and B only — no spurious C/D slots ✓")


# ---------------------------------------------------------------------------
# Test 6: 4-document prompt has A, B, C, D slots
# ---------------------------------------------------------------------------

async def test_4_doc_prompt():
    docs = [
        {"id": 25, "title": "Doc 25", "filename": "doc25.pdf", "jurisdiction": "EU"},
        {"id": 23, "title": "Doc 23", "filename": "doc23.pdf", "jurisdiction": "US"},
        {"id": 27, "title": "Doc 27", "filename": "doc27.pdf", "jurisdiction": "UK"},
        {"id": 99, "title": "Doc 99", "filename": "doc99.pdf", "jurisdiction": "CA"},
    ]
    prompt = await run_comparison(docs)

    for label in ("A", "B", "C", "D"):
        assert f"Document {label}" in prompt, f"Document {label} missing from 4-doc prompt"
    assert "DOCUMENT D ANALYSIS" in prompt, "Document D slot missing from 4-doc prompt"
    print("[TEST P6] 4-doc prompt has A, B, C, D slots ✓")


# ---------------------------------------------------------------------------
# Test 7: Zero-chunk document C → forced slot and "No relevant chunks" text
# ---------------------------------------------------------------------------

CAPTURED_CONTEXTS: list[str] = []

async def test_zero_chunk_doc_has_forced_slot():
    docs = [
        {"id": 25, "title": "Doc 25", "filename": "doc25.pdf", "jurisdiction": "EU"},
        {"id": 23, "title": "Doc 23", "filename": "doc23.pdf", "jurisdiction": "US"},
        {"id": 27, "title": "Doc 27", "filename": "doc27.pdf", "jurisdiction": "UK"},
    ]

    CAPTURED_PROMPTS.clear()
    CAPTURED_CONTEXTS.clear()

    async def _capture(question, context):
        CAPTURED_PROMPTS.append(question)
        CAPTURED_CONTEXTS.append(context)
        return "[MOCK]"

    rag_mod.ask_copilot_with_context = _capture
    await compare_documents(db=None, question="Compare", documents=docs, limit=5)
    rag_mod.ask_copilot_with_context = _capturing_copilot

    prompt_c = CAPTURED_PROMPTS[2]
    ctx_c = CAPTURED_CONTEXTS[2]

    # Evidence is now embedded in the PROMPT (not the context stub).
    # The zero-chunk notice for doc27 must appear in its MAP prompt.
    assert "No relevant chunks were retrieved" in prompt_c, \
        "Zero-chunk notice for doc27 missing from prompt (evidence should be embedded in prompt)"
    # The forced per-document slot for C must be in the PROMPT
    assert "Document C" in prompt_c, \
        "Document C forced slot missing from prompt even though 0 chunks were retrieved"
    # Context stub should be minimal (not the full evidence block)
    assert len(ctx_c) < 200, f"Context stub is too large ({len(ctx_c)} chars) — evidence may not be embedded in prompt"
    print("[TEST P7] Zero-chunk doc: forced slot in prompt ✓, zero-chunk notice in prompt ✓, context stub minimal ✓")


# ---------------------------------------------------------------------------
# Test 11: Evidence is self-contained in the prompt — not displaced to context
# ---------------------------------------------------------------------------

async def test_evidence_embedded_in_prompt():
    """
    Verify that for a 5-document comparison the full evidence for ALL 5 docs
    appears in the prompt= argument to ask_copilot_with_context(), NOT only
    in the context= argument. This is the fix for the attention-degradation
    bug that caused Documents D and E to be silently omitted.
    """
    docs = [
        {"id": 25, "title": "Doc 25", "filename": "doc25.pdf", "jurisdiction": "EU"},
        {"id": 23, "title": "Doc 23", "filename": "doc23.pdf", "jurisdiction": "US"},
        {"id": 27, "title": "Doc 27", "filename": "doc27.pdf", "jurisdiction": "UK"},
        {"id": 99, "title": "Doc 99", "filename": "doc99.pdf", "jurisdiction": "CA"},
        {"id": 98, "title": "Doc 98", "filename": "doc98.pdf", "jurisdiction": "AU"},
    ]

    # Extend mock to handle doc 98
    import app.services.rag_service as _rm
    original_search = _rm.search_similar_chunks
    def _mock5(db, query, limit, distance_threshold=0.80, document_ids=None):
        if document_ids and 98 in document_ids:
            return []
        return _mock_search(db, query, limit, distance_threshold, document_ids)
    _rm.search_similar_chunks = _mock5

    CAPTURED_PROMPTS.clear()
    CAPTURED_CONTEXTS.clear()

    async def _capture(question, context):
        CAPTURED_PROMPTS.append(question)
        CAPTURED_CONTEXTS.append(context)
        return "[MOCK]"

    rag_mod.ask_copilot_with_context = _capture
    await compare_documents(db=None, question="Compare these documents", documents=docs, limit=5)
    rag_mod.ask_copilot_with_context = _capturing_copilot
    _rm.search_similar_chunks = original_search

    reduce_prompt = CAPTURED_PROMPTS[-1]
    reduce_ctx = CAPTURED_CONTEXTS[-1]

    # All 5 filenames must appear in the reduce prompt
    for doc in docs:
        assert doc["filename"] in reduce_prompt, \
            f"{doc['filename']} missing from REDUCE prompt"

    # All 5 document IDs must appear in the reduce prompt
    for doc in docs:
        assert str(doc["id"]) in reduce_prompt, \
            f"ID {doc['id']} missing from REDUCE prompt"

    # The context stub must be short
    assert len(reduce_ctx) < 200, \
        f"Context stub is too large ({len(reduce_ctx)} chars)"

    # All 5 labels must be in the reduce prompt
    for label in ["A", "B", "C", "D", "E"]:
        assert f"Document {label}" in reduce_prompt, f"Document {label} missing from 5-doc prompt"

    print("[TEST P11] 5-doc: all evidence embedded in prompt, context stub is minimal ✓")
    print(f"           prompt chars = {len(reduce_prompt)}, context stub chars = {len(reduce_ctx)}")


# ---------------------------------------------------------------------------
# Test 8: No out-of-scope document IDs in sources
# ---------------------------------------------------------------------------

async def test_no_out_of_scope_sources():
    docs = [
        {"id": 25, "title": "Doc 25", "filename": "doc25.pdf", "jurisdiction": "EU"},
        {"id": 23, "title": "Doc 23", "filename": "doc23.pdf", "jurisdiction": "US"},
        {"id": 27, "title": "Doc 27", "filename": "doc27.pdf", "jurisdiction": "UK"},
    ]
    CAPTURED_PROMPTS.clear()
    original_search = rag_mod.search_similar_chunks
    original_ask = rag_mod.ask_copilot_with_context
    rag_mod.search_similar_chunks = _mock_search
    rag_mod.ask_copilot_with_context = _capturing_copilot
    try:
        result = await compare_documents(db=None, question="Compare", documents=docs, limit=5)
    finally:
        rag_mod.search_similar_chunks = original_search
        rag_mod.ask_copilot_with_context = original_ask
    all_ids = {src["document_id"] for src_list in result["sources"].values() for src in src_list}
    assert all_ids <= {25, 23, 27}, f"Out-of-scope IDs in sources: {all_ids - {25, 23, 27}}"
    print("[TEST P8] No out-of-scope document IDs in sources ✓")


# ---------------------------------------------------------------------------
# Test 9: CONCLUSION line references all_labels count
# ---------------------------------------------------------------------------

async def test_conclusion_references_all_labels():
    docs = [
        {"id": 25, "title": "Doc 25", "filename": "doc25.pdf", "jurisdiction": "EU"},
        {"id": 23, "title": "Doc 23", "filename": "doc23.pdf", "jurisdiction": "US"},
        {"id": 27, "title": "Doc 27", "filename": "doc27.pdf", "jurisdiction": "UK"},
    ]
    prompt = await run_comparison(docs)

    assert "CONCLUSION" in prompt
    # The conclusion instruction must mention all labels
    assert "A, B, C" in prompt, "Conclusion instruction missing label list A, B, C"
    print("[TEST P9] CONCLUSION instruction references A, B, C ✓")


# ---------------------------------------------------------------------------
# Test 10: Normal /rag/ask untouched
# ---------------------------------------------------------------------------

def test_normal_rag_ask_untouched():
    src = pathlib.Path("app/routers/rag.py").read_text()
    assert "answer_with_rag" in src
    assert "compare_documents" not in src
    assert "investigation_id" in src
    print("[TEST P10] /rag/ask router untouched ✓")


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

async def main():
    print("\n=== PROMPT STRUCTURE TESTS ===\n")
    await test_prompt_contains_all_three_labels()
    await test_required_participants_header()
    await test_per_document_section_header()
    await test_deterministic_filename_per_slot()
    await test_2_doc_prompt_no_spurious_labels()
    await test_4_doc_prompt()
    await test_zero_chunk_doc_has_forced_slot()
    await test_no_out_of_scope_sources()
    await test_conclusion_references_all_labels()
    await test_evidence_embedded_in_prompt()
    test_normal_rag_ask_untouched()
    print("\n=== ALL PROMPT TESTS PASSED ===\n")

if __name__ == "__main__":
    asyncio.run(main())
