"""add investigation queries table

Revision ID: 59fe5b4888e9
Revises: 0825e082b03c
Create Date: 2026-09-10 13:21:27.064611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fe5b4888e9'
down_revision: Union[str, Sequence[str], None] = '0825e082b03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_queries_id'), 'investigation_queries', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_queries_investigation_id'), 'investigation_queries', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_queries_investigation_id'), table_name='investigation_queries')
    op.drop_index(op.f('ix_investigation_queries_id'), table_name='investigation_queries')
    op.drop_table('investigation_queries')
    # ### end Alembic commands ###
