"""add investigation review fields

Revision ID: 92b41a221a35
Revises: 9f5da628d800
Create Date: 2026-09-30 10:53:03.206038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b41a221a35'
down_revision: Union[str, Sequence[str], None] = '9f5da628d800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('review_status', sa.String(length=50), nullable=True))
    op.add_column('investigations', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.add_column('investigations', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'investigations', 'users', ['reviewer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investigations', type_='foreignkey')
    op.drop_column('investigations', 'reviewed_at')
    op.drop_column('investigations', 'reviewer_id')
    op.drop_column('investigations', 'review_status')
    # ### end Alembic commands ###
