"""add_investigation_comments_table

Revision ID: 9f5da628d800
Revises: 7d2fc10c4803
Create Date: 2026-09-30 10:30:50.636629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5da628d800'
down_revision: Union[str, Sequence[str], None] = '7d2fc10c4803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_comments_id'), 'investigation_comments', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_comments_investigation_id'), 'investigation_comments', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_comments_user_id'), 'investigation_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_comments_user_id'), table_name='investigation_comments')
    op.drop_index(op.f('ix_investigation_comments_investigation_id'), table_name='investigation_comments')
    op.drop_index(op.f('ix_investigation_comments_id'), table_name='investigation_comments')
    op.drop_table('investigation_comments')
    # ### end Alembic commands ###
