"""Add apple_id to users

Revision ID: bd37296f0223
Revises: f8cec2da480b
Create Date: 2026-10-01 11:17:40.994049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd37296f0223'
down_revision: Union[str, Sequence[str], None] = 'f8cec2da480b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('apple_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['apple_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'apple_id')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
