"""Add KnowledgePost

Revision ID: ca59d9159840
Revises: a1b2c3d4e5f6
Create Date: 2026-09-23 19:10:06.039243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca59d9159840'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_citation', sa.Text(), nullable=True),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_posts_id'), 'knowledge_posts', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_posts_user_id'), 'knowledge_posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_posts_user_id'), table_name='knowledge_posts')
    op.drop_index(op.f('ix_knowledge_posts_id'), table_name='knowledge_posts')
    op.drop_table('knowledge_posts')
    # ### end Alembic commands ###
