"""create research queries table

Revision ID: d668c26622f4
Revises: e3622783f108
Create Date: 2026-09-08 08:41:00.887602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd668c26622f4'
down_revision: Union[str, Sequence[str], None] = 'e3622783f108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column(
    "created_at",
    sa.DateTime(),
    server_default=sa.text("CURRENT_TIMESTAMP"),
    nullable=True,
),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_queries')
    # ### end Alembic commands ###
