"""add risk fields to agent run

Revision ID: 8f2cb633b412
Revises: 92b41a221a35
Create Date: 2026-09-30 11:49:01.356371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2cb633b412'
down_revision: Union[str, Sequence[str], None] = '92b41a221a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('risk_level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'risk_level')
    op.drop_column('agent_runs', 'risk_score')
    # ### end Alembic commands ###
