"""Add collaborator and presence tables

Revision ID: cb366a166bd7
Revises: 848c2bda2a25
Create Date: 2026-10-09 21:27:20.978697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb366a166bd7'
down_revision: Union[str, Sequence[str], None] = '848c2bda2a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_collaborators_id'), 'investigation_collaborators', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_collaborators_investigation_id'), 'investigation_collaborators', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_collaborators_user_id'), 'investigation_collaborators', ['user_id'], unique=False)
    op.create_table('investigation_presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_presence_id'), 'investigation_presence', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_presence_investigation_id'), 'investigation_presence', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_presence_user_id'), 'investigation_presence', ['user_id'], unique=False)





    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_presence_user_id'), table_name='investigation_presence')
    op.drop_index(op.f('ix_investigation_presence_investigation_id'), table_name='investigation_presence')
    op.drop_index(op.f('ix_investigation_presence_id'), table_name='investigation_presence')
    op.drop_table('investigation_presence')
    op.drop_index(op.f('ix_investigation_collaborators_user_id'), table_name='investigation_collaborators')
    op.drop_index(op.f('ix_investigation_collaborators_investigation_id'), table_name='investigation_collaborators')
    op.drop_index(op.f('ix_investigation_collaborators_id'), table_name='investigation_collaborators')
    op.drop_table('investigation_collaborators')
    # ### end Alembic commands ###
