"""
LLM Provider abstraction.

Supports:
  - MockLLMProvider  : deterministic, no external deps (used in DEMO_MODE)
  - OllamaLLMProvider: calls local Ollama instance

The active provider is chosen by the LLM_PROVIDER env var:
  LLM_PROVIDER=mock    → MockLLMProvider
  LLM_PROVIDER=ollama  → OllamaLLMProvider
"""

from __future__ import annotations

import json
import logging
import textwrap
from abc import ABC, abstractmethod
from typing import Any

import httpx

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Base interface
# ---------------------------------------------------------------------------


class LLMProvider(ABC):
    """Abstract LLM provider interface."""

    @abstractmethod
    async def generate(self, prompt: str, system: str | None = None) -> str:
        """Generate a response for a given prompt."""
        ...

    @abstractmethod
    async def stream(self, prompt: str, system: str | None = None):
        """Yield tokens as they are generated."""
        ...

    async def structured_output(
        self,
        prompt: str,
        schema: dict[str, Any],
        system: str | None = None,
    ) -> dict[str, Any]:
        """
        Request a JSON-structured response.
        Default implementation: generate → JSON parse.
        Override in subclasses for native structured output support.
        """
        json_prompt = (
            f"{prompt}\n\nRespond ONLY with valid JSON matching this schema:\n"
            f"{json.dumps(schema, indent=2)}"
        )
        raw = await self.generate(json_prompt, system=system)
        # Strip markdown fences if present
        raw = raw.strip()
        if raw.startswith("```"):
            raw = raw.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            logger.warning("LLM did not return valid JSON; returning raw text")
            return {"raw": raw}


# ---------------------------------------------------------------------------
# Mock provider (always available)
# ---------------------------------------------------------------------------

DEMO_RESPONSES: dict[str, str] = {
    "default": textwrap.dedent("""
        **Demo Mode Response**

        This response is generated by the MockLLMProvider because either
        `LLM_PROVIDER=mock` is set or Ollama is unavailable.

        To enable real AI responses, configure Ollama:
        ```
        OLLAMA_BASE_URL=http://localhost:11434
        OLLAMA_MODEL=llama3.2
        LLM_PROVIDER=ollama
        ```

        *[DEMO — not a real AI response]*
    """).strip(),
    "gdpr": textwrap.dedent("""
        **GDPR Data Retention Requirements**

        Under the GDPR (Regulation (EU) 2016/679), data retention is governed
        primarily by Article 5(1)(e) — the **storage limitation** principle:

        > Personal data shall be kept in a form which permits identification of
        > data subjects for no longer than is necessary for the purposes for
        > which the personal data are processed.

        **Key requirements:**
        1. Data must not be kept longer than necessary for its original purpose.
        2. Organizations must define and document retention periods per data category.
        3. Data must be deleted or anonymized once the retention period expires.
        4. Exceptions apply for archiving in the public interest, scientific/historical
           research, or statistical purposes (Art. 89).

        **[GDPR Art. 5(1)(e)]** — Storage limitation principle
        **[GDPR Art. 17]** — Right to erasure ('right to be forgotten')
        **[GDPR Art. 30]** — Records of processing activities must include retention info

        *[DEMO — not a real AI response]*
    """).strip(),
}


class MockLLMProvider(LLMProvider):
    """Deterministic mock provider for demo/testing without external deps."""

    async def generate(self, prompt: str, system: str | None = None) -> str:
        prompt_lower = prompt.lower()
        if "gdpr" in prompt_lower and "retention" in prompt_lower:
            return DEMO_RESPONSES["gdpr"]
        return DEMO_RESPONSES["default"]

    async def stream(self, prompt: str, system: str | None = None):
        response = await self.generate(prompt, system=system)
        for word in response.split(" "):
            yield word + " "

    async def structured_output(
        self,
        prompt: str,
        schema: dict[str, Any],
        system: str | None = None,
    ) -> dict[str, Any]:
        return {
            "demo": True,
            "message": "MockLLMProvider — structured output not supported in demo mode.",
        }


# ---------------------------------------------------------------------------
# Ollama provider
# ---------------------------------------------------------------------------


class OllamaLLMProvider(LLMProvider):
    """LLM provider backed by a local Ollama instance."""

    def __init__(self, base_url: str, model: str, timeout: float = 120.0):
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.timeout = timeout

    async def generate(self, prompt: str, system: str | None = None) -> str:
        messages = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.model,
            "messages": messages,
            "stream": False,
        }

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            try:
                resp = await client.post(
                    f"{self.base_url}/api/chat",
                    json=payload,
                )
                resp.raise_for_status()
                data = resp.json()
                return data["message"]["content"]
            except httpx.ConnectError:
                logger.error("Cannot connect to Ollama at %s", self.base_url)
                raise
            except Exception as exc:
                logger.error("Ollama request failed: %s", exc)
                raise

    async def stream(self, prompt: str, system: str | None = None):
        messages = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.model,
            "messages": messages,
            "stream": True,
        }

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            async with client.stream(
                "POST", f"{self.base_url}/api/chat", json=payload
            ) as resp:
                async for line in resp.aiter_lines():
                    if not line.strip():
                        continue
                    try:
                        data = json.loads(line)
                        token = data.get("message", {}).get("content", "")
                        if token:
                            yield token
                    except json.JSONDecodeError:
                        continue

    async def is_available(self) -> bool:
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                resp = await client.get(f"{self.base_url}/api/tags")
                return resp.status_code == 200
        except Exception:
            return False


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------


def get_llm_provider() -> LLMProvider:
    """
    Return the appropriate LLM provider based on configuration.
    Falls back to MockLLMProvider if Ollama is not configured or unavailable.
    """
    from app.config import settings

    if settings.llm_provider == "ollama":
        logger.info(
            "Using OllamaLLMProvider (model=%s, base_url=%s)",
            settings.ollama_model,
            settings.ollama_base_url,
        )
        return OllamaLLMProvider(
            base_url=settings.ollama_base_url,
            model=settings.ollama_model,
        )

    logger.info("Using MockLLMProvider (DEMO_MODE)")
    return MockLLMProvider()


# Singleton instance (lazy)
_provider: LLMProvider | None = None


def get_provider() -> LLMProvider:
    global _provider
    if _provider is None:
        _provider = get_llm_provider()
    return _provider
